name = "github-achievements-api"
main = "src/index.ts"
compatibility_date = "2025-02-27"

[env.preview]
name = "github-achievements-api-preview"
# Asegúrate de que el entorno de vista previa tenga la misma configuración que el entorno principal 